name: "PR Checklist Validation"
on:
  pull_request:
    types: [opened, edited, synchronize]
permissions:
  pull-requests: write
  checks: write
jobs:
  check-pr-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Reset checklist on push
        if: github.event.action == 'synchronize'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            let prBody = pr.body || '';

            // チェック済みのアイテムを未チェック状態に戻す
            const resetBody = prBody.replace(/^- \[x\]/gm, '- [ ]');

            if (resetBody !== prBody) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: resetBody
              });
            }

      - name: Check PR Checklist
        id: check-checklist
        run: |
          # PRの本文からチェックリストを抽出
          pr_body='${{ github.event.pull_request.body }}'

          # チェックリストアイテムの総数を取得
          total_items=$(echo "$pr_body" | grep -c "^- \[" || echo "0")

          # チェック済みアイテムの数を取得
          checked_items=$(echo "$pr_body" | grep -c "^- \[x\]" || echo "0")

          echo "Total checklist items: $total_items"
          echo "Checked items: $checked_items"

          # チェックリストが存在しない場合は警告
          if [ $total_items -eq 0 ]; then
            echo "::warning::PRテンプレートにチェックリストが見つかりません"
            exit 0
          fi

          # synchronizeイベントの場合は、チェックリストがリセットされるので常に失敗
          if [ "${{ github.event.action }}" == "synchronize" ]; then
            echo "新しいコミットがpushされました。チェックリストを再確認してください"
            exit 1
          fi

          # 全てのチェックが完了しているかチェック
          if [ $checked_items -eq $total_items ]; then
            echo "全てのチェックリストアイテムが完了しています"
            
            # チェック済みアイテムのコメントをチェック
            echo "$pr_body" > /tmp/pr_body.txt
            
            # チェック済みアイテムのコメントが記入されているかチェック
            missing_comments=0
            while IFS= read -r line; do
              if [[ "$line" =~ ^-\ \[x\] ]]; then
                # 次の行がコメント行かチェック
                next_line=$(grep -A1 -F "$line" /tmp/pr_body.txt | tail -n1)
                if [[ "$next_line" =~ ^[[:space:]]*コメント:[[:space:]]*$ ]] || [[ ! "$next_line" =~ ^[[:space:]]*コメント: ]]; then
                  missing_comments=$((missing_comments + 1))
                fi
              fi
            done <<< "$pr_body"
            
            if [ $missing_comments -gt 0 ]; then
              echo "チェック済みアイテムにコメントが記入されていません ($missing_comments件)"
              exit 1
            fi
            
            echo "全てのチェックリストアイテムが完了し、コメントも記入されています"
          else
            echo "チェックリストの完了が必要です ($checked_items/$total_items)"
            exit 1
          fi
