name: "PR Checklist Validation"
on:
  pull_request:
    types: [opened, edited, synchronize]
permissions:
  pull-requests: write
  checks: write
jobs:
  check-pr-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Reset checklist on push
        if: github.event.action == 'synchronize'
        uses: actions/github-script@v6
        with:
          script: |
            console.log('新しいコミットがpushされました。チェックリストをリセットします');
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            let prBody = pr.body || '';

            // チェック済みのアイテムを未チェック状態に戻す
            const resetBody = prBody.replace(/^- \[x\]/gm, '- [ ]');

            if (resetBody !== prBody) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: resetBody
              });
            }

      - name: Check PR Checklist
        uses: actions/github-script@v6
        with:
          script: |
            console.log('ワークフローが開始されました');
            console.log('イベント名:', context.eventName);
            console.log('アクション:', context.payload.action);

            // PRの本文からチェックリストを抽出
            const prBody = context.payload.pull_request.body || '';

            // チェックリストアイテムの総数を取得
            const totalItems = (prBody.match(/^- \[/gm) || []).length;

            // チェック済みアイテムの数を取得
            const checkedItems = (prBody.match(/^- \[x\]/gm) || []).length;

            console.log(`チェックリスト進捗: ${checkedItems}/${totalItems}`);

            // チェックリストが存在しない場合は警告
            if (totalItems === 0) {
              console.log('::warning::PRテンプレートにチェックリストが見つかりません');
              return;
            }

            // synchronizeイベントの場合は、チェックリストがリセットされるので常に失敗
            if (context.payload.action === 'synchronize') {
              console.log('新しいコミットがpushされました。チェックリストを再確認してください');
              process.exit(1);
            }

            // 全てのチェックが完了しているかチェック
            if (checkedItems === totalItems) {
              console.log('全てのチェックリストアイテムが完了しています');
            } else {
              console.log(`チェックリストの完了が必要です (${checkedItems}/${totalItems})`);
              process.exit(1);
            }
